global class AdyenInterface {
//    global static AuthoriseResponse authorisePayment(String merchantRecord, adyen_payments.OASPaymentsRequest request) {
//        Merchant__mdt merchant = Util.getConfigByName(merchantRecord);
//        return AdyenClient.authorisePayment(merchant, request);
//    }
//    global static CaptureResponse capturePayment(String merchantRecord, CaptureRequest request) {
//        Merchant__mdt merchant = Util.getConfigByName(merchantRecord);
//        return AdyenClient.capturePayment(merchant, request);
//    }
//    global static DisableResponse disablePaymentMethod(String merchantRecord, DisableRequest request) {
//        Merchant__mdt merchant = Util.getConfigByName(merchantRecord);
//        return AdyenClient.disablePaymentMethod(merchant, request);
//    }
//    global static AuthoriseResponse updatePaymentMethod(String merchantRecord, AuthoriseRequest request) {
//        Merchant__mdt merchant = Util.getConfigByName(merchantRecord);
//        return AdyenClient.updatePaymentMethod(merchant, request);
//    }
}