//
// Represents and Adyen MerchantApplication. Hard-coded
/*
“merchantApplication”:{
       “name”:“YOUR_PLUGIN”,
       “version”:“YOUR_PLUGIN_VERSION”
    }
        ar.applicationInfo.merchantApplication.version = '0.1';
        ar.applicationInfo.merchantApplication.name = 'adyen-salesforce-b2b-commerce';

*/
public class MerchantApplication {
    public String name = 'adyen-salesforce-b2b-commerce';
    public String version = '1.0.0';
}