//
// Represents and Adyen PaymentSource. Hard-coded
/*
“adyenPaymentSource”:{
       “name”:“YOUR_PLUGIN”,
       “version”:“YOUR_PLUGIN_VERSION”
    }
        ar.applicationInfo.adyenPaymentSource.version = '0.1';
        ar.applicationInfo.adyenPaymentSource.name = 'adyen-salesforce-b2b-commerce';

*/
public class PaymentSource {
    public String name = 'adyen-salesforce-b2b-commerce';
    public String version = '0.1';
}