//
// Represents and Adyen ExternalPlatform. Hard-coded
/*
  “externalPlatform”:{
       “name”:“PLATFORM_NAME”,
       “version”:“PLATFORM_VERSION”,
       “integrator”:“YOUR_SYSTEM_INTEGRATOR_NAME”
    }
            ar.applicationInfo.externalPlatform.name = 'SalesforceB2BCommerce';
        ar.applicationInfo.externalPlatform.integrator = 'Appsolutely';
        ar.applicationInfo.externalPlatform.version = '40';

*/
public class ExternalPlatform {
    public String name = 'SalesforceB2BCommerce';
    public String version = '40';
    public String integrator = 'Appsolutely';
}